global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  # TODO 换成自己的监控服务器地址
  # 这里还可以结合其他服务发现工具，比如 consul
  - job_name: 'example-nodejs-app'
    static_configs:
      - targets: ['host.docker.internal:3002']
  # prometheus 服务自身监控
  # - job_name: 'prometheus'
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #     - targets: ['host.docker.internal:9090']
  # consul 服务发现
  - job_name: "consul-example"
    consul_sd_configs:
      - server:   'host.docker.internal:8500'
        services: ['auth', 'api', 'load-balancer', 'postgres']
        token: '{{ key "consul_token" }}'

    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex:         '(.*)'
        target_label:  'job'
        replacement:   '$1'
      - source_labels: ['__meta_consul_node']
        regex:         '(.*)'
        target_label:  'instance'
        replacement:   '$1'
      - source_labels: ['__meta_consul_tags']
        regex:         ',(production|canary),'
        target_label:  'group'
        replacement:   '$1'
rule_files:
  - 'alert-rules.yml'
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['host.docker.internal:9093']